<template>
  <div class="list">
    <ul is="transition-group">
      <li v-for="story in stories" :key="story['.key']">
        <span>{{story.title}}</span>
        <button v-on:click="openStory(story)">Open</button>
        <button v-on:click="deleteStory(story)">Delete</button>
      </li>
    </ul>
    <button v-on:click="createStory()">Share a new story</button>
  </div>
</template>

<script>
import {db} from '../firebase'

var storiesRef = db.ref('stories')

export default {
  name: 'list',
  data: () => ({
    stories: {}
  }),
  firebase: {
    stories: {
      source: storiesRef,
      // Optional, allows you to handle any errors.
      cancelCallback (err) {
        console.error(err)
      }
    }
  },
  methods: {
    openStory: function (story) {
      console.log(story)
    },
    createStory: function () {
      const titles = ['Cool story, bro', 'Awesome story', 'True story', 'Unforgettable story', 'That\'s another story', 'Yet another story']
      const newStoryRef = storiesRef.push({
        title: titles[Math.floor(Math.random() * titles.length)]
      })
      // Get the unique ID generated by push() by accessing its key
      console.log(newStoryRef.key)
    },
    deleteStory: function (story) {
      storiesRef.child(story['.key']).remove()
    }
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

.list {
  margin: 1em 1.5em;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  display: flex;
  margin: 1em 0;
  transition: all .25s ease;
}

.v-enter, .v-leave-active {
  color: #fff;
}

li > span {
  flex-grow: 1;
}

</style>
